import type { Translation } from '../../types';
type CommonContent = Pick<Translation, 'appName' | 'tagline' | 'navigation' | 'search' | 'account' | 'signedOut' | 'notifications' | 'cancel' | 'delete' | 'clear'>;
export const common: CommonContent = {
  appName: '流光清单',
  tagline: '把今天，安排得刚刚好',
  navigation: {
    today: '今天',
    completed: '已完成',
    calendar: '日历',
    milestones: '倒数纪念日',
    groups: '分组',
    trash: '垃圾桶',
  },
  search: {
    title: '搜索任务',
    placeholder: '输入关键词…',
    clear: '清除搜索',
    close: '关闭搜索',
    tasks: '任务',
    shortcut: 'Esc 关闭 · Enter 打开任务',
    resultCount: (count) => `${count} 项结果`,
    idleTitle: '查找你的任务',
    idleDescription: '输入标题、详情内容或分组名称开始搜索。',
    emptyTitle: '没有找到任务',
    emptyDescription: '换一个关键词，或检查任务是否已移至垃圾桶。',
  },
  account: {
    localAccount: '本地账户',
    settings: '设置',
    signOut: '退出登录',
    signOutTitle: '退出当前会话？',
    signOutMessage: '任务数据不会被删除，重新进入后仍可继续使用。',
  },
  signedOut: {
    title: '登录 LightFlux',
    description: '使用邮箱密码或验证码登录，在不同设备间安全同步任务。',
    continue: '进入本地模式',
    passwordMethod: '密码',
    otpMethod: '验证码',
    emailPlaceholder: '邮箱地址',
    passwordPlaceholder: '密码（至少 8 位）',
    signInWithPassword: '登录',
    signingInWithPassword: '正在登录…',
    registerWithPassword: '创建账户',
    registeringWithPassword: '正在创建…',
    createAccount: '首次使用？创建账户',
    useExistingAccount: '已有账户？返回登录',
    passwordTooShort: '密码至少需要 8 位。',
    passwordSignInError: '邮箱或密码不正确。',
    registrationError: '账户创建失败；邮箱可能已注册。',
    registrationCodeSent: '验证码已发送，请完成邮箱验证。',
    registrationCodeDescription: (email) => `输入发送至 ${email} 的注册验证码`,
    verifyRegistration: '验证并完成注册',
    sendCode: '发送验证码',
    sendingCode: '正在发送…',
    codeDescription: (email) => `验证码已发送至 ${email}`,
    codePlaceholder: '输入 6 位验证码',
    verifyCode: '验证并登录',
    verifyingCode: '正在验证…',
    resendCode: '重新发送',
    changeEmail: '更换邮箱',
    codeSent: '新的验证码已发送。',
    invalidEmail: '请输入有效的邮箱地址。',
    invalidCode: '请输入完整的 6 位验证码。',
    requestError: '验证码发送失败，请稍后重试。',
    verifyError: '验证码无效或已过期，请重新输入。',
    setPasswordDescription: '设置一个密码，下次可直接用邮箱和密码登录。',
    passwordConfirmPlaceholder: '再次输入密码',
    setPasswordAction: '设置密码',
    settingPassword: '正在设置…',
    skipPassword: '暂不设置，直接进入',
    passwordMismatch: '两次输入的密码不一致。',
    setPasswordError: '密码设置失败，请稍后重试。',
  },
  notifications: {
    orderUpdated: '顺序已更新',
    saveFailed: '保存失败，本地数据仍会保留，请稍后重试',
    taskCompleted: [
      '完成一项，真棒！',
      '又搞定一件事 🎉',
      '干得漂亮，继续保持！',
      '效率满分，向前一步 ✨',
      '完成！给自己点个赞。',
    ],
    allTasksDone: '今日任务全部完成，太厉害了！🎊',
    taskReopened: '已重新标记为待办',
    taskMovedToGroup: (groupName) => `已移动到「${groupName}」`,
    taskRescheduled: '日期已更新',
    priorityUpdated: '优先级已更新',
  },
  cancel: '取消',
  delete: '删除',
  clear: '清除',
};
