import type { Translation } from '../../types';
export const statistics: Translation['statistics'] = {
  eyebrow: '',
  title: '统计',
  subtitle: '查看任务节奏与完成规律',
  back: '返回',
  ranges: {
    '7d': '7 天',
    '30d': '30 天',
    '90d': '90 天',
    year: '今年',
  },
  estimated: '含迁移前估算',
  completedTasks: '完成任务',
  completionRate: '计划完成率',
  pendingChange: '待办净变化',
  currentOverdue: '当前延期',
  completedDetail: (count) => `${count} 条完成记录`,
  rateDelta: (delta) => `较上一周期${delta >= 0 ? '提高' : '下降'} ${Math.abs(delta)} 个百分点`,
  rateNoComparison: '上一周期暂无足够计划数据',
  pendingDetail: (created, completed) => `新增 ${created} · 完成 ${completed}`,
  overdueDetail: (count) => `其中高优先级 ${count} 项`,
  trendTitle: '计划与完成节奏',
  trendDescription: '同一时间段内计划处理的任务与实际完成数',
  planned: '计划',
  completed: '完成',
  insightsEyebrow: '值得关注',
  insightsTitle: '从数据到下一步',
  stableTitle: '稳定完成日',
  stableDescription: (days, advantage) => `${days}的计划完成率比周期均值高 ${advantage} 个百分点。`,
  pressureInsightTitle: (group) => `${group}仍有积压`,
  pressureInsightDescription: (pending, overdue) => `当前待处理 ${pending} 项，其中 ${overdue} 项已延期。`,
  reduceTitle: '安排建议',
  reduceDescription: (day, gap) => `${day}平均少完成 ${gap} 项，可减少当天计划量。`,
  buildingTitle: '数据正在积累',
  buildingDescription: '继续安排并完成任务后，这里会生成可执行建议。',
  viewTasks: '查看相关任务',
  pressureTitle: '任务压力分布',
  pressureDescription: '哪些分组贡献了完成量，哪些仍有积压',
  pending: '仍待处理',
  weeklyTitle: '每周规律',
  weeklyDescription: '按计划日期计算的完成率',
  noPlannedTasks: '暂无计划任务',
  weekdays: ['周日', '周一', '周二', '周三', '周四', '周五', '周六'],
  definition: '计划完成率 = 统计周期内已完成的计划任务 ÷ 该周期计划任务总数。回收站任务不计入，数据仅在本地聚合。',
  estimatedDefinition: '当前周期包含升级前的迁移数据，反复完成、重开或改期的旧历史可能不完整；升级后的事件会被准确记录。',
};
