import type { Translation } from '../../types';
export const desktop: Translation['desktop'] = {
  newVersionAvailable: (version) => `Version ${version} is available`,
  updateToVersion: (version) => `Update to ${version}`,
  settings: {
    general: 'General',
    softwareUpdate: 'Software update',
    updateReminderOptions: {
      sidebarAndToast: 'Sidebar icon and one notice',
      sidebar: 'Sidebar icon only',
      settingsOnly: 'Settings only',
    },
    dockVisibilityOptions: {
      always: 'Always show',
      windowOpen: 'Show with window',
      hidden: 'Hide; use menu bar',
    },
    dockBadgeOptions: {
      today: 'Incomplete today',
      overdue: 'Overdue only',
      none: 'Do not show',
    },
    closeBehaviorOptions: {
      hide: 'Hide to menu bar',
      quit: 'Quit LightFlux',
    },
    updateChecking: 'Checking…',
    updateDownloading: (progress) => `Downloading ${progress}%`,
    updateReady: 'Ready to restart',
    updateAvailable: (version) => `${version} available`,
    updateCurrent: 'Up to date',
    updateCheckedAtLaunch: 'Checked at launch',
    updateSigningRequired: 'Release signing required',
    tryAgain: 'Try again later.',
    updateFallbackBody: 'Includes improvements and stability fixes.',
    updateCheckDescription: 'Check quietly after launch without delaying the first screen',
    currentVersion: 'Current version',
    restartUpdate: 'Restart',
    downloadUpdate: 'Download',
    checkNow: 'Check now',
    autoDownloadDescription: 'Download regular updates in the background and ask before restart',
    autoDownload: 'Download in background',
    updateReminderDescription: 'Choose where the minimal update entry appears',
    updateReminder: 'Update reminder',
    dockIconDescription: 'Choose the LightFlux icon shown in the Dock at runtime',
    dockIcon: 'Dock icon',
    dockIcons: {
      flux: 'Flux',
      paper: 'Paper',
      graphite: 'Graphite',
    },
    dockVisibilityDescription: 'The menu bar can reopen the window when the Dock is hidden',
    dockVisibility: 'Dock visibility',
    dockBadgeDescription: 'Show the most useful task count on the icon',
    dockBadge: 'Dock badge',
    closeBehaviorDescription: 'Menu bar mode can keep LightFlux running',
    closeBehavior: 'When the last window closes',
  },
  updateMenu: {
    ready: 'Update ready',
    downloading: 'Downloading update',
    failed: 'Update failed',
    available: (version) => `LightFlux ${version} is available`,
    close: 'Close update details',
    currentVersion: (version) => `Current version ${version}`,
    required: 'Required update',
    stable: 'Stable release',
    tryAgain: 'Please try again later.',
    fallbackBody: 'Includes improvements and stability fixes.',
    later: 'Cancel',
    skip: 'Skip this version',
    download: 'Update now',
    downloadingProgress: 'Downloading…',
    restart: 'Restart and finish update',
  },
};
