import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  screen: {
    backgroundColor: '#F6F5F8',
    flex: 1,
  },
  safeArea: {
    flex: 1,
  },
  scroll: {
    alignSelf: 'center',
    maxWidth: 1040,
    width: '100%',
  },
  content: {
    paddingBottom: 24,
    paddingHorizontal: 20,
  },
  contentCompact: {
    paddingBottom: 22,
    paddingHorizontal: 18,
  },
  header: {
    paddingBottom: 12,
    paddingTop: 14,
  },
  headerCompact: {
    paddingBottom: 10,
    paddingTop: 8,
  },
  headerWithAction: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  title: {
    color: '#28293A',
    fontSize: 22,
    fontWeight: '600',
  },
  titleCompact: {
    fontSize: 18,
    fontWeight: '600',
  },
  section: {
    marginBottom: 16,
  },
  sectionCompact: {
    marginBottom: 13,
  },
  sectionTitle: {
    color: '#303143',
    fontSize: 13,
    fontWeight: '600',
    marginBottom: 6,
    marginLeft: 2,
  },
  sectionTitleCompact: {
    fontSize: 12,
    fontWeight: '500',
    marginBottom: 5,
    marginLeft: 1,
  },
  sectionCard: {
    backgroundColor: '#FFFFFF',
    borderColor: '#E3E2E9',
    borderRadius: 8,
    borderWidth: 1,
    overflow: 'hidden',
  },
  sectionCardCompact: {
    backgroundColor: 'transparent',
    borderRadius: 0,
    borderWidth: 0,
  },
  settingRow: {
    alignItems: 'center',
    borderBottomColor: '#EBEAF0',
    borderBottomWidth: 1,
    flexDirection: 'row',
    minHeight: 66,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  settingRowCompact: {
    minHeight: 42,
    paddingHorizontal: 2,
    paddingVertical: 6,
  },
  settingRowSimple: {
    minHeight: 48,
    paddingVertical: 7,
  },
  settingRowStacked: {
    alignItems: 'stretch',
    flexDirection: 'column',
  },
  settingRowFocused: {
    backgroundColor: '#F4F2FF',
    borderLeftColor: '#6759E8',
    borderLeftWidth: 3,
    paddingLeft: 11,
  },
  settingCopy: {
    flex: 1,
    marginRight: 20,
  },
  settingCopyCompact: {
    marginRight: 12,
  },
  settingCopySimple: {
    marginRight: 16,
  },
  settingCopyStacked: {
    marginBottom: 14,
    marginRight: 0,
  },
  settingTitle: {
    color: '#303143',
    fontSize: 13,
    fontWeight: '500',
  },
  settingTitleCompact: {
    fontSize: 13,
    fontWeight: '400',
  },
  settingDescription: {
    color: '#81828F',
    fontSize: 11,
    lineHeight: 17,
    marginTop: 6,
  },
  settingControl: {
    alignItems: 'flex-end',
  },
  controlStacked: {
    alignItems: 'stretch',
    width: '100%',
  },
  select: {
    alignItems: 'center',
    backgroundColor: '#F3F3F6',
    borderColor: '#DEDEE6',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 38,
    paddingHorizontal: 12,
  },
  selectCompact: {
    borderRadius: 8,
    minHeight: 34,
    paddingHorizontal: 10,
  },
  selectHovered: {
    backgroundColor: '#FFFFFF',
    borderColor: '#C9C6DB',
  },
  selectOpen: {
    backgroundColor: '#FFFFFF',
    borderColor: '#9E95E9',
    shadowColor: '#6759E8',
    shadowOffset: { height: 0, width: 0 },
    shadowOpacity: 0.12,
    shadowRadius: 6,
  },
  selectText: {
    color: '#4F5060',
    flex: 1,
    fontSize: 13,
    fontWeight: '400',
    marginRight: 10,
  },
  selectTextCompact: {
    fontSize: 12,
    fontWeight: '400',
  },
  controlPressed: {
    opacity: 0.76,
    transform: [{ scale: 0.98 }],
  },
  toggle: {
    backgroundColor: '#D8D7DF',
    borderColor: '#CBCAD4',
    borderRadius: 12,
    borderWidth: 1,
    height: 24,
    justifyContent: 'center',
    paddingHorizontal: 2,
    width: 44,
  },
  toggleActive: {
    backgroundColor: '#6759E8',
    borderColor: '#6759E8',
  },
  toggleCompact: {
    borderRadius: 11,
    height: 22,
    width: 40,
  },
  toggleThumb: {
    backgroundColor: '#FFFFFF',
    borderRadius: 9,
    height: 18,
    shadowColor: '#2E2C40',
    shadowOffset: { height: 1, width: 0 },
    shadowOpacity: 0.14,
    shadowRadius: 2,
    width: 18,
  },
  toggleThumbActive: {
    alignSelf: 'flex-end',
  },
  toggleThumbCompact: {
    borderRadius: 8,
    height: 16,
    width: 16,
  },
  linkRow: {
    alignItems: 'center',
    borderLeftColor: 'transparent',
    borderLeftWidth: 3,
    flexDirection: 'row',
    minHeight: 56,
    paddingHorizontal: 14,
  },
  linkRowCompact: {
    borderLeftWidth: 0,
    minHeight: 42,
    paddingHorizontal: 2,
  },
  linkRowHovered: {
    backgroundColor: '#F8F7FB',
  },
  linkRowPressed: {
    backgroundColor: '#EEEBFF',
  },
  linkIcon: {
    alignItems: 'center',
    backgroundColor: '#EDE9FF',
    borderRadius: 8,
    height: 32,
    justifyContent: 'center',
    marginRight: 10,
    width: 32,
  },
  linkIconCompact: {
    backgroundColor: 'transparent',
    borderRadius: 0,
    height: 24,
    marginRight: 8,
    width: 24,
  },
  linkCopy: {
    flex: 1,
    marginRight: 12,
  },
  updateNotice: {
    alignItems: 'flex-start',
    backgroundColor: '#F1EEFF',
    borderColor: '#D8D2FA',
    borderLeftColor: '#6759E8',
    borderLeftWidth: 3,
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    marginBottom: 10,
    padding: 12,
  },
  updateNoticeError: {
    backgroundColor: '#FFF2F4',
    borderColor: '#F0CDD3',
    borderLeftColor: '#C95A69',
  },
  noticeCopy: {
    flex: 1,
    marginLeft: 10,
  },
  noticeTitle: {
    color: '#3D3E50',
    fontSize: 12,
    fontWeight: '600',
  },
  noticeDescription: {
    color: '#737481',
    fontSize: 11,
    lineHeight: 16,
    marginTop: 4,
  },
  versionControl: {
    alignItems: 'center',
    backgroundColor: '#F7F7F9',
    borderColor: '#E2E1E8',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 42,
    paddingHorizontal: 8,
    paddingLeft: 14,
  },
  versionText: {
    color: '#4C4D5E',
    fontSize: 12,
    fontWeight: '500',
  },
  versionState: {
    color: '#92939F',
    fontSize: 9,
    marginTop: 3,
  },
  dockIconOptions: {
    flexDirection: 'row',
    width: '100%',
  },
  dockIconOption: {
    alignItems: 'center',
    backgroundColor: '#F7F7F9',
    borderColor: '#E1E0E7',
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    marginHorizontal: 4,
    minHeight: 86,
    padding: 10,
  },
  dockIconOptionSelected: {
    backgroundColor: '#F0EEFF',
    borderColor: '#8E83E4',
  },
  dockIconOptionHovered: {
    borderColor: '#B9B2F2',
    transform: [{ translateY: -1 }],
  },
  dockIconPreview: {
    alignItems: 'center',
    backgroundColor: '#6759E8',
    borderColor: 'rgba(255,255,255,0.35)',
    borderRadius: 12,
    borderWidth: 1,
    height: 48,
    justifyContent: 'center',
    overflow: 'hidden',
    position: 'relative',
    shadowColor: '#3A355E',
    shadowOffset: { height: 4, width: 0 },
    shadowOpacity: 0.18,
    shadowRadius: 8,
    width: 48,
  },
  dockIconPreviewSelected: {
    shadowOpacity: 0.24,
  },
  dockIconPaper: {
    backgroundColor: '#FFFFFF',
    borderColor: '#DFDCEB',
  },
  dockIconGraphite: {
    backgroundColor: '#343440',
  },
  dockIconLine: {
    backgroundColor: '#CFC9FF',
    borderRadius: 2,
    height: 3,
    left: 13,
    position: 'absolute',
    top: 14,
    width: 14,
  },
  dockIconLinePaper: {
    backgroundColor: '#AAA0F2',
  },
  dockIconDot: {
    backgroundColor: '#CFC9FF',
    borderRadius: 3,
    bottom: 11,
    height: 6,
    position: 'absolute',
    right: 11,
    width: 6,
  },
  dockIconDotPaper: {
    backgroundColor: '#AAA0F2',
  },
  dockIconLabel: {
    color: '#777886',
    fontSize: 10,
    fontWeight: '500',
    marginTop: 8,
  },
  dockIconLabelSelected: {
    color: '#6759E8',
  },
});

export default styles;
