import type { Translation } from '../../types';
export const settings: Translation['settings'] = {
  title: '设置',
  languageTitle: '语言',
  chinese: '简体中文',
  english: 'English',
  dataTitle: '数据与统计',
  statisticsTitle: '统计',
  statisticsDescription: '查看完成节奏、任务压力与安排规律',
  shortcutsTitle: '键盘快捷键',
  shortcutSearch: '搜索任务',
  shortcutClose: '关闭详情或菜单',
  shortcutBold: '粗体',
  shortcutItalic: '斜体',
  shortcutHeading: '一级标题',
  shortcutList: '无序列表',
  shortcutQuote: '引用',
  shortcutCode: '代码块',
  keySearch: '⌘ / Ctrl + F',
  keyClose: 'Esc',
  keyBold: '⌘ / Ctrl + B',
  keyItalic: '⌘ / Ctrl + I',
  keyHeading: '# + 空格',
  keyList: '- + 空格',
  keyQuote: '> + 空格',
  keyCode: '``` + 空格',
};
