import type { Translation } from '../../types';
export const settings: Translation['settings'] = {
  title: '设置',
  accountTitle: '账户',
  localOnly: '仅本地',
  editProfileName: '编辑账户名称',
  profileNamePlaceholder: '账户名称',
  saveProfile: '保存账户名称',
  changeAvatar: '更换头像',
  profileUpdated: '账户资料已更新',
  profileUpdateError: '账户资料更新失败，请稍后重试。',
  avatarPermissionDenied: '需要照片权限才能选择头像。',
  avatarUploadError: '头像上传失败，请换一张图片重试。',
  signIn: '登录',
  signOut: '退出登录',
  languageTitle: '语言',
  chinese: '简体中文',
  english: 'English',
  dataTitle: '数据与统计',
  statisticsTitle: '统计',
  visibleViewsTitle: '显示页面',
};
