import type { AgentOperation, AgentPreviewField, AgentRisk } from '../agent/types';
import type { TodoFilter, TodoPriority } from '../types/todo';
export interface Translation {
  appName: string;
  tagline: string;
  navigation: {
    today: string;
    completed: string;
    calendar: string;
    milestones: string;
    groups: string;
    trash: string;
  };
  search: {
    title: string;
    placeholder: string;
    clear: string;
    close: string;
    tasks: string;
    shortcut: string;
    resultCount: (count: number) => string;
    idleTitle: string;
    idleDescription: string;
    emptyTitle: string;
    emptyDescription: string;
  };
  completed: {
    title: string;
    count: (count: number) => string;
    today: string;
    yesterday: string;
    emptyTitle: string;
    emptyDescription: string;
  };
  account: {
    localAccount: string;
    settings: string;
    signOut: string;
    signOutTitle: string;
    signOutMessage: string;
  };
  settings: {
    title: string;
    languageTitle: string;
    chinese: string;
    english: string;
    dataTitle: string;
    statisticsTitle: string;
    statisticsDescription: string;
    visibleViewsTitle: string;
    visibleViewsDescription: (view: string) => string;
  };
  desktop: {
    newVersionAvailable: (version: string) => string;
    updateToVersion: (version: string) => string;
    settings: {
      general: string;
      languageDescription: string;
      softwareUpdate: string;
      updateReminderOptions: {
        sidebarAndToast: string;
        sidebar: string;
        settingsOnly: string;
      };
      dockVisibilityOptions: {
        always: string;
        windowOpen: string;
        hidden: string;
      };
      dockBadgeOptions: {
        today: string;
        overdue: string;
        none: string;
      };
      closeBehaviorOptions: {
        hide: string;
        quit: string;
      };
      updateChecking: string;
      updateDownloading: (progress: number) => string;
      updateReady: string;
      updateAvailable: (version: string) => string;
      updateCurrent: string;
      updateCheckedAtLaunch: string;
      updateSigningRequired: string;
      tryAgain: string;
      updateFallbackBody: string;
      updateCheckDescription: string;
      currentVersion: string;
      restartUpdate: string;
      downloadUpdate: string;
      checkNow: string;
      autoDownloadDescription: string;
      autoDownload: string;
      updateReminderDescription: string;
      updateReminder: string;
      dockIconDescription: string;
      dockIcon: string;
      dockIcons: {
        flux: string;
        paper: string;
        graphite: string;
      };
      dockVisibilityDescription: string;
      dockVisibility: string;
      dockBadgeDescription: string;
      dockBadge: string;
      closeBehaviorDescription: string;
      closeBehavior: string;
    };
    updateMenu: {
      ready: string;
      downloading: string;
      failed: string;
      available: (version: string) => string;
      close: string;
      currentVersion: (version: string) => string;
      required: string;
      stable: string;
      tryAgain: string;
      fallbackBody: string;
      later: string;
      skip: string;
      download: string;
      downloadingProgress: string;
      restart: string;
    };
  };
  statistics: {
    eyebrow: string;
    title: string;
    subtitle: string;
    back: string;
    ranges: {
      '7d': string;
      '30d': string;
      '90d': string;
      year: string;
    };
    estimated: string;
    completedTasks: string;
    completionRate: string;
    pendingChange: string;
    currentOverdue: string;
    completedDetail: (count: number) => string;
    rateDelta: (delta: number) => string;
    rateNoComparison: string;
    pendingDetail: (created: number, completed: number) => string;
    overdueDetail: (count: number) => string;
    trendTitle: string;
    trendDescription: string;
    planned: string;
    completed: string;
    insightsEyebrow: string;
    insightsTitle: string;
    stableTitle: string;
    stableDescription: (days: string, advantage: number) => string;
    pressureInsightTitle: (group: string) => string;
    pressureInsightDescription: (pending: number, overdue: number) => string;
    reduceTitle: string;
    reduceDescription: (day: string, gap: number) => string;
    buildingTitle: string;
    buildingDescription: string;
    viewTasks: string;
    pressureTitle: string;
    pressureDescription: string;
    pending: string;
    weeklyTitle: string;
    weeklyDescription: string;
    noPlannedTasks: string;
    weekdays: string[];
    definition: string;
    estimatedDefinition: string;
  };
  signedOut: {
    title: string;
    description: string;
    continue: string;
    emailPlaceholder: string;
    sendCode: string;
    sendingCode: string;
    codeDescription: (email: string) => string;
    codePlaceholder: string;
    verifyCode: string;
    verifyingCode: string;
    resendCode: string;
    changeEmail: string;
    codeSent: string;
    invalidEmail: string;
    invalidCode: string;
    requestError: string;
    verifyError: string;
  };
  notifications: {
    orderUpdated: string;
    saveFailed: string;
    taskCompleted: string[];
    allTasksDone: string;
    taskReopened: string;
    taskMovedToGroup: (groupName: string) => string;
    taskRescheduled: string;
    priorityUpdated: string;
  };
  inputPlaceholder: string;
  addTask: string;
  filters: Record<TodoFilter, string>;
  clearCompleted: string;
  emptyTitle: Record<TodoFilter, string>;
  emptyDescription: Record<TodoFilter, string>;
  deleteTask: string;
  deleteTitle: string;
  deleteMessage: string;
  cancel: string;
  delete: string;
  clearTitle: string;
  clearMessage: string;
  clear: string;
  markComplete: string;
  markActive: string;
  calendar: {
    title: string;
    monthTitle: (year: number, month: number) => string;
    weekdays: string[];
    previousMonth: string;
    nextMonth: string;
    today: string;
    selectedDate: string;
    tasksForDate: (count: number) => string;
    empty: string;
    inputPlaceholder: string;
  };
  groups: {
    title: string;
    ungrouped: string;
    addGroup: string;
    groupPlaceholder: string;
    taskPlaceholder: string;
    addTaskTitle: string;
    cancelTask: string;
    reorderTask: string;
    addGroupAbove: string;
    addGroupBelow: string;
    renameGroup: string;
    deleteGroup: string;
    confirmAdd: string;
    confirmRename: string;
    deleteGroupTitle: string;
    deleteGroupMessage: string;
    count: (count: number) => string;
    expand: string;
    collapse: string;
  };
  editor: {
    title: string;
    titlePlaceholder: string;
    bodyPlaceholder: string;
    close: string;
    bold: string;
    italic: string;
    heading: string;
    bulletList: string;
    orderedList: string;
    quote: string;
    inlineCode: string;
    codeBlock: string;
    undo: string;
    redo: string;
    image: string;
    imageUrl: string;
    insertImage: string;
    invalidImageUrl: string;
    imageUploading: string;
    imageUploadNotConfigured: string;
    imageUploadTooLarge: string;
    imageUploadUnsupported: string;
    imageUploadFailed: string;
    emptyTitle: string;
    previewTitle: string;
    resizePane: string;
    metadataTitle: string;
    dateLabel: string;
    groupLabel: string;
    priorityLabel: string;
    scheduleToday: string;
    scheduleTomorrow: string;
    clearDate: string;
    noDate: string;
  };
  agent: {
    title: string;
    shortcut: string;
    close: string;
    empty: string;
    inputPlaceholder: string;
    send: string;
    thinking: string;
    clarification: string;
    proposal: string;
    assumptions: string;
    confirm: string;
    reject: string;
    undo: string;
    applied: string;
    undone: string;
    requestFailed: string;
    resultReportFailed: string;
    undoFailed: string;
    previewFields: Record<AgentPreviewField, string>;
    valueYes: string;
    valueNo: string;
    valueEmpty: string;
    relativePosition: (
      title: string,
      position: 'before' | 'after',
    ) => string;
    affectedTasks: (count: number) => string;
    historyPending: string;
    historyExecuted: string;
    historyUndone: string;
    historyRejected: string;
    historyInvalid: string;
    risk: Record<AgentRisk, string>;
    operations: Record<AgentOperation['type'], string>;
  };
  milestones: {
    title: string;
    count: (count: number) => string;
    add: string;
    addTemplate: string;
    templates: {
      anniversary: string;
      countdown: string;
      birthday: string;
      holiday: string;
      custom: string;
    };
    filters: {
      all: string;
      anniversary: string;
      countdown: string;
      birthday: string;
      holiday: string;
      custom: string;
      archived: string;
    };
    emptyTitle: string;
    emptyArchived: string;
    titlePlaceholder: string;
    calendar: string;
    repeat: string;
    solar: string;
    lunar: string;
    repeatYearly: string;
    oneTime: string;
    year: string;
    month: string;
    day: string;
    startYear: string;
    notes: string;
    notesPlaceholder: string;
    reminders: string;
    reminderDay: (days: number) => string;
    reminderToday: string;
    reminderInDays: (days: number) => string;
    leapMonth: string;
    leapMonthFallback: string;
    leapMonthSkip: string;
    lunarDayThirtySkip: string;
    februaryFallback: string;
    february28: string;
    march1: string;
    style: string;
    save: string;
    cancel: string;
    today: string;
    tomorrow: string;
    remainingDays: (days: number) => string;
    pastDays: (days: number) => string;
    anniversaryYears: (years: number) => string;
    birthdayYears: (years: number) => string;
    lunarDate: string;
    pinned: string;
    archived: string;
    edit: string;
    pin: string;
    unpin: string;
    editStyle: string;
    editNotes: string;
    createTask: string;
    archive: string;
    unarchive: string;
    moveToTrash: string;
    restored: string;
    trashed: string;
    created: string;
    updated: string;
    relatedTaskCreated: string;
    invalidDate: string;
    notificationPermissionDenied: string;
    moreActions: string;
    todaySection: string;
    openMilestones: string;
  };
  taskMenu: {
    addSubtask: string;
    rename: string;
    priority: string;
    priorityOptions: Record<TodoPriority, string>;
    subtaskPlaceholder: string;
    createSubtask: string;
    moveToGroup: string;
    backToActions: string;
    moveToTrash: string;
    moreActions: string;
  };
  trash: {
    title: string;
    emptyTitle: string;
    restore: string;
    deleteForever: string;
    deleteForeverTitle: string;
    deleteForeverMessage: string;
    emptyTrash: string;
    emptyTrashTitle: string;
    emptyTrashMessage: string;
    preview: string;
    tasksSection: string;
    milestonesSection: string;
    deleteMilestoneForeverTitle: string;
    deleteMilestoneForeverMessage: string;
  };
}
