import type { Translation } from '../../types';
export const agent: Translation['agent'] = {
  title: 'AI task assistant',
  shortcut: 'Cmd / Ctrl + J',
  close: 'Close AI assistant',
  empty: 'Tell me what task to create, find, or change. You will confirm changes first.',
  inputPlaceholder: 'For example: Remind me to file expenses tomorrow',
  send: 'Send to AI assistant',
  thinking: 'Understanding and preparing a plan…',
  clarification: 'Clarification',
  proposal: 'Operation preview',
  assumptions: 'Assumptions',
  confirm: 'Confirm',
  reject: 'Cancel',
  undo: 'Undo last AI operation',
  applied: 'AI operations applied',
  undone: 'AI operations undone',
  requestFailed: 'Unable to reach the AI assistant. Try again.',
  resultReportFailed: 'Changes were applied, but the result was not reported.',
  undoFailed: 'Task data changed, so this operation cannot be safely undone.',
  previewFields: {
    title: 'Title',
    scheduledDate: 'Date',
    priority: 'Priority',
    project: 'Project',
    parent: 'Parent task',
    completed: 'Completion',
    position: 'Position',
    type: 'Type',
    dateRule: 'Date rule',
    startYear: 'Start year',
    reminders: 'Reminders',
    notes: 'Notes',
    icon: 'Icon',
    color: 'Color',
    pinned: 'Pinned',
    archived: 'Archived',
    trashed: 'Trash',
  },
  valueYes: 'Yes',
  valueNo: 'No',
  valueEmpty: 'Not set',
  relativePosition: (title, position) =>
    `${position === 'before' ? 'Before' : 'After'} ${title}`,
  affectedTasks: (count) => `${count} ${count === 1 ? 'task' : 'tasks'} affected`,
  historyPending: 'Awaiting confirmation',
  historyExecuted: 'Executed',
  historyUndone: 'Undone',
  historyRejected: 'Cancelled',
  historyInvalid: 'No longer valid',
  risk: {
    low: 'Low risk',
    medium: 'Medium risk',
    high: 'High risk',
  },
  operations: {
    'task.create': 'Create task',
    'task.update': 'Update task',
    'task.set_completion': 'Set completion',
    'task.move': 'Move task',
    'task.trash': 'Move to trash',
    'task.restore': 'Restore task',
    'project.create': 'Create project',
    'project.update': 'Update project',
    'milestone.create': 'Create milestone',
    'milestone.update': 'Update milestone',
    'milestone.archive': 'Archive milestone',
    'milestone.unarchive': 'Unarchive milestone',
    'milestone.restore': 'Restore milestone',
    'milestone.trash': 'Move milestone to trash',
  },
};
