import type { Translation } from '../../types';
export const milestones: Translation['milestones'] = {
  title: 'Milestones',
  count: (count) => `${count} ${count === 1 ? 'milestone' : 'milestones'}`,
  add: 'Add milestone',
  addTemplate: 'Choose milestone type',
  templates: {
    anniversary: 'Anniversary',
    countdown: 'Countdown',
    birthday: 'Birthday',
    holiday: 'Holiday',
    custom: 'Custom',
  },
  filters: {
    all: 'All',
    anniversary: 'Anniversary',
    countdown: 'Countdown',
    birthday: 'Birthday',
    holiday: 'Holiday',
    custom: 'Custom',
    archived: 'Archived',
  },
  emptyTitle: 'No milestones yet',
  emptyArchived: 'No archived milestones',
  titlePlaceholder: 'Milestone name',
  calendar: 'Calendar',
  repeat: 'Repeat',
  solar: 'Solar',
  lunar: 'Lunar',
  repeatYearly: 'Repeat yearly',
  oneTime: 'One time',
  year: 'Year',
  month: 'Month',
  day: 'Day',
  startYear: 'Start year (optional)',
  notes: 'Notes',
  notesPlaceholder: 'Add a short note…',
  reminders: 'Reminders',
  reminderDay: (days) => (days === 0 ? 'On the day' : `${days} days before`),
  reminderToday: 'This milestone is today',
  reminderInDays: (days) => `${days} days to go`,
  leapMonth: 'Leap month',
  leapMonthFallback: 'Use regular month when unavailable',
  leapMonthSkip: 'Skip years without this leap month',
  lunarDayThirtySkip: 'Skip lunar years where this month has no day 30',
  februaryFallback: 'Non-leap-year rule',
  february28: 'Use February 28',
  march1: 'Use March 1',
  style: 'Theme color',
  save: 'Save milestone',
  cancel: 'Cancel',
  today: 'Today',
  tomorrow: 'Tomorrow',
  remainingDays: (days) => `${days} days left`,
  pastDays: (days) => `${days} days ago`,
  anniversaryYears: (years) => `${years} year anniversary`,
  birthdayYears: (years) => `Age ${years}`,
  lunarDate: 'Lunar',
  pinned: 'Pinned',
  archived: 'Archived',
  edit: 'Edit',
  pin: 'Pin',
  unpin: 'Unpin',
  editStyle: 'Change style',
  editNotes: 'Edit notes',
  createTask: 'Create related task',
  archive: 'Archive',
  unarchive: 'Unarchive',
  moveToTrash: 'Move to trash',
  restored: 'Milestone restored',
  trashed: 'Milestone moved to trash',
  created: 'Milestone created',
  updated: 'Milestone updated',
  relatedTaskCreated: 'Related task created',
  invalidDate: 'Enter a valid date',
  notificationPermissionDenied: 'Allow system notifications to enable reminders',
  moreActions: 'More milestone actions',
  todaySection: "Today's milestones",
  openMilestones: 'Open milestones',
};
