import type { Translation } from '../../types';
export const agent: Translation['agent'] = {
  title: 'AI 任务助理',
  shortcut: '⌘ / Ctrl + J',
  close: '关闭 AI 助理',
  empty: '告诉我你想新增、查找或调整什么任务。修改内容会先让你确认。',
  inputPlaceholder: '例如：明天提醒我报销，优先级设为高',
  send: '发送给 AI 助理',
  thinking: '正在理解并生成计划…',
  clarification: '需要确认',
  proposal: '操作预览',
  assumptions: '当前假设',
  confirm: '确认执行',
  reject: '取消',
  undo: '撤销上一次 AI 操作',
  applied: 'AI 操作已执行',
  undone: 'AI 操作已撤销',
  requestFailed: 'AI 请求失败，请稍后重试。',
  resultReportFailed: '操作已执行，但未能回传结果。',
  undoFailed: '数据已变化，无法安全撤销。',
  previewFields: {
    title: '标题',
    scheduledDate: '日期',
    priority: '优先级',
    group: '分组',
    parent: '父任务',
    completed: '完成状态',
    position: '位置',
    type: '类型',
    dateRule: '日期规则',
    startYear: '起始年份',
    reminders: '提醒',
    notes: '备注',
    icon: '图标',
    color: '颜色',
    pinned: '置顶',
    archived: '归档',
    trashed: '垃圾桶',
  },
  valueYes: '是',
  valueNo: '否',
  valueEmpty: '未设置',
  relativePosition: (title, position) =>
    `${title} ${position === 'before' ? '之前' : '之后'}`,
  affectedTasks: (count) => `影响 ${count} 项任务`,
  historyPending: '等待确认',
  historyExecuted: '已执行',
  historyUndone: '已撤销',
  historyRejected: '已取消',
  historyInvalid: '已失效',
  risk: {
    low: '低风险',
    medium: '中风险',
    high: '高风险',
  },
  operations: {
    'task.create': '新增任务',
    'task.update': '修改任务',
    'task.set_completion': '设置完成状态',
    'task.move': '移动任务',
    'task.trash': '移至垃圾桶',
    'task.restore': '恢复任务',
    'group.create': '新增分组',
    'group.update': '修改分组',
    'milestone.create': '新增节点',
    'milestone.update': '修改节点',
    'milestone.archive': '归档节点',
    'milestone.unarchive': '取消归档节点',
    'milestone.restore': '恢复节点',
    'milestone.trash': '移至垃圾桶',
  },
};
