import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  screen: {
    backgroundColor: '#F7F7FA',
    flex: 1,
  },
  safeArea: {
    flex: 1,
  },
  scroll: {
    alignSelf: 'center',
    maxWidth: 1080,
    width: '100%',
  },
  content: {
    paddingBottom: 42,
    paddingHorizontal: 22,
    paddingTop: 18,
  },
  header: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    marginBottom: 24,
    paddingRight: 90,
  },
  backButton: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#E2E2EA',
    borderRadius: 12,
    borderWidth: 1,
    height: 40,
    justifyContent: 'center',
    marginRight: 15,
    width: 40,
  },
  backButtonPressed: {
    backgroundColor: '#F0EEFF',
    transform: [{ scale: 0.94 }],
  },
  headerText: {
    flex: 1,
  },
  eyebrow: {
    color: '#7B6FE1',
    fontFamily: 'monospace',
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 1.1,
    marginBottom: 5,
  },
  title: {
    color: '#28293A',
    fontSize: 27,
    fontWeight: '800',
    letterSpacing: -0.6,
  },
  subtitle: {
    color: '#777886',
    fontSize: 13,
    marginTop: 6,
  },
  rangeSelector: {
    backgroundColor: '#ECECF1',
    borderColor: '#DCDCE4',
    borderRadius: 13,
    borderWidth: 1,
    flexDirection: 'row',
    marginBottom: 24,
    padding: 4,
  },
  rangeButton: {
    alignItems: 'center',
    borderRadius: 9,
    flex: 1,
    justifyContent: 'center',
    minHeight: 36,
  },
  rangeButtonSelected: {
    backgroundColor: '#FFFFFF',
    shadowColor: '#3E3B55',
    shadowOffset: { height: 2, width: 0 },
    shadowOpacity: 0.08,
    shadowRadius: 5,
  },
  rangeText: {
    color: '#686976',
    fontSize: 12,
    fontWeight: '700',
  },
  rangeTextSelected: {
    color: '#6759E8',
  },
  periodRow: {
    alignItems: 'center',
    flexDirection: 'row',
    marginBottom: 8,
    paddingHorizontal: 2,
  },
  periodText: {
    color: '#90919D',
    fontFamily: 'monospace',
    fontSize: 11,
    letterSpacing: 0.4,
  },
  estimatedPill: {
    backgroundColor: '#FFF3BF',
    borderRadius: 8,
    marginLeft: 9,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  estimatedText: {
    color: '#A46B00',
    fontSize: 10,
    fontWeight: '700',
  },
  metricGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginHorizontal: -6,
  },
  metricCell: {
    padding: 6,
  },
  metricCard: {
    backgroundColor: '#FFFFFF',
    borderColor: '#E4E3EA',
    borderRadius: 14,
    borderWidth: 1,
    minHeight: 145,
    overflow: 'hidden',
    padding: 17,
    position: 'relative',
  },
  metricAccent: {
    borderBottomRightRadius: 3,
    borderTopRightRadius: 3,
    bottom: 17,
    left: 0,
    position: 'absolute',
    top: 17,
    width: 3,
  },
  metricLabel: {
    color: '#666775',
    fontSize: 12,
    fontWeight: '600',
  },
  metricValue: {
    fontSize: 30,
    fontWeight: '800',
    letterSpacing: -0.7,
    marginTop: 13,
  },
  metricDetail: {
    color: '#8A8B98',
    fontSize: 11,
    lineHeight: 16,
    marginTop: 11,
  },
  card: {
    backgroundColor: '#FFFFFF',
    borderColor: '#E4E3EA',
    borderRadius: 14,
    borderWidth: 1,
    marginTop: 18,
    padding: 20,
  },
  sectionHeader: {
    flex: 1,
  },
  sectionTitle: {
    color: '#303143',
    fontSize: 16,
    fontWeight: '800',
  },
  sectionDescription: {
    color: '#8B8C98',
    fontSize: 11,
    lineHeight: 16,
    marginTop: 5,
  },
  trendHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  legend: {
    alignItems: 'center',
    flexDirection: 'row',
    marginTop: 4,
  },
  legendItem: {
    alignItems: 'center',
    flexDirection: 'row',
    marginLeft: 12,
  },
  legendDot: {
    borderRadius: 3,
    height: 8,
    marginRight: 5,
    width: 10,
  },
  legendPlanned: {
    backgroundColor: '#E3DCFF',
    borderColor: '#C4B6FF',
    borderWidth: 1,
  },
  legendCompleted: {
    backgroundColor: '#8B6DF2',
  },
  legendPending: {
    backgroundColor: '#FFE28A',
  },
  legendText: {
    color: '#8A8B98',
    fontSize: 10,
  },
  chart: {
    height: 220,
    marginTop: 18,
    paddingLeft: 30,
    position: 'relative',
  },
  chartGridLine: {
    backgroundColor: '#ECECF1',
    height: 1,
    left: 30,
    position: 'absolute',
    right: 0,
  },
  chartGridLabel: {
    color: '#A0A1AC',
    fontFamily: 'monospace',
    fontSize: 9,
    position: 'absolute',
    right: '100%',
    top: -6,
    width: 26,
  },
  chartBuckets: {
    bottom: 0,
    flexDirection: 'row',
    left: 38,
    position: 'absolute',
    right: 3,
    top: 8,
  },
  chartBucket: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'flex-end',
    minWidth: 42,
  },
  chartBars: {
    alignItems: 'flex-end',
    flexDirection: 'row',
    height: 155,
    justifyContent: 'center',
    width: '100%',
  },
  plannedBar: {
    backgroundColor: '#E3DCFF',
    borderColor: '#C4B6FF',
    borderRadius: 6,
    borderWidth: 1,
    marginHorizontal: 2,
    maxWidth: 24,
    width: '28%',
  },
  completedBar: {
    backgroundColor: '#8B6DF2',
    borderRadius: 6,
    marginHorizontal: 2,
    maxWidth: 24,
    width: '28%',
  },
  chartBucketLabel: {
    color: '#8E8F9C',
    fontSize: 9,
    marginTop: 7,
    maxWidth: 76,
  },
  insightsCard: {
    borderLeftColor: '#A88BFF',
    borderLeftWidth: 3,
  },
  insightsHeading: {
    marginBottom: 14,
  },
  insightsEyebrow: {
    color: '#9697A3',
    fontFamily: 'monospace',
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 0.8,
    marginBottom: 5,
  },
  insightList: {
    gap: 9,
  },
  insight: {
    backgroundColor: '#F1F1F4',
    borderColor: 'transparent',
    borderRadius: 11,
    borderWidth: 1,
    flexDirection: 'row',
    padding: 13,
  },
  insightWarning: {
    backgroundColor: '#FFF9DF',
    borderColor: '#F3D66E',
  },
  insightIcon: {
    alignItems: 'center',
    backgroundColor: '#E9E5FF',
    borderRadius: 10,
    height: 30,
    justifyContent: 'center',
    marginRight: 11,
    width: 30,
  },
  insightIconWarning: {
    backgroundColor: '#FFF0B3',
  },
  insightBody: {
    flex: 1,
  },
  insightTitle: {
    color: '#363747',
    fontSize: 12,
    fontWeight: '800',
  },
  insightDescription: {
    color: '#777885',
    fontSize: 11,
    lineHeight: 16,
    marginTop: 4,
  },
  insightAction: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    flexDirection: 'row',
    marginTop: 7,
  },
  insightActionText: {
    color: '#6759E8',
    fontSize: 11,
    fontWeight: '700',
    marginRight: 4,
  },
  lowerGrid: {
    flexDirection: 'row',
    marginHorizontal: -9,
  },
  lowerGridCompact: {
    flexDirection: 'column',
  },
  lowerCell: {
    flex: 1,
    paddingHorizontal: 9,
  },
  pressureList: {
    gap: 14,
    marginTop: 4,
  },
  pressureRow: {
    alignItems: 'center',
    flexDirection: 'row',
  },
  pressureName: {
    color: '#646573',
    fontSize: 11,
    marginRight: 10,
    width: 58,
  },
  pressureTrack: {
    flex: 1,
    height: 10,
  },
  pressureScale: {
    backgroundColor: '#FFE28A',
    borderRadius: 6,
    height: 10,
    overflow: 'hidden',
  },
  pressureCompleted: {
    backgroundColor: '#8B6DF2',
    height: '100%',
  },
  pressureValue: {
    color: '#9394A0',
    fontFamily: 'monospace',
    fontSize: 10,
    marginLeft: 10,
    textAlign: 'right',
    width: 55,
  },
  emptyText: {
    color: '#92939F',
    fontSize: 12,
    marginVertical: 26,
    textAlign: 'center',
  },
  weekdayChart: {
    alignItems: 'flex-end',
    flexDirection: 'row',
    height: 174,
    justifyContent: 'space-between',
    marginTop: 4,
  },
  weekdayColumn: {
    alignItems: 'center',
    flex: 1,
  },
  weekdayRate: {
    color: '#92939F',
    fontFamily: 'monospace',
    fontSize: 9,
    marginBottom: 5,
  },
  weekdayBarArea: {
    alignItems: 'center',
    borderBottomColor: '#E9E9EF',
    borderBottomWidth: 1,
    height: 120,
    justifyContent: 'flex-end',
    width: '100%',
  },
  weekdayBar: {
    backgroundColor: '#5EDCB8',
    borderRadius: 6,
    maxWidth: 30,
    width: '54%',
  },
  weekdayBarStrong: {
    backgroundColor: '#20C997',
  },
  weekdayLabel: {
    color: '#777885',
    fontSize: 9,
    marginTop: 7,
    maxWidth: 42,
  },
  definition: {
    backgroundColor: '#ECECF1',
    borderColor: '#D9D9E2',
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: 'row',
    marginTop: 18,
    padding: 13,
  },
  definitionIcon: {
    alignItems: 'center',
    backgroundColor: '#E1DCFF',
    borderRadius: 10,
    height: 22,
    justifyContent: 'center',
    marginRight: 10,
    width: 22,
  },
  definitionText: {
    color: '#858692',
    flex: 1,
    fontSize: 10,
    lineHeight: 16,
  },
  pressed: {
    opacity: 0.7,
    transform: [{ scale: 0.98 }],
  },
  contentCompact: {
    paddingBottom: 24,
    paddingHorizontal: 16,
    paddingTop: 12,
  },
  headerCompact: {
    marginBottom: 16,
    paddingRight: 0,
  },
  titleCompact: {
    fontSize: 22,
    letterSpacing: -0.4,
  },
  eyebrowCompact: {
    fontSize: 10,
    marginBottom: 3,
  },
});

export default styles;
