import type { Translation } from '../../types';
export const statistics: Translation['statistics'] = {
  eyebrow: '',
  title: 'Statistics',
  subtitle: 'Review your task rhythm and completion patterns',
  back: 'Back',
  ranges: {
    '7d': '7 days',
    '30d': '30 days',
    '90d': '90 days',
    year: 'This year',
  },
  estimated: 'Includes migrated estimates',
  completedTasks: 'Completed tasks',
  completionRate: 'Planned completion',
  pendingChange: 'Pending net change',
  currentOverdue: 'Currently overdue',
  completedDetail: (count) => `${count} completion ${count === 1 ? 'record' : 'records'}`,
  rateDelta: (delta) => `${Math.abs(delta)} points ${delta >= 0 ? 'higher' : 'lower'} than the previous period`,
  rateNoComparison: 'Not enough planned data in the previous period',
  pendingDetail: (created, completed) => `${created} created · ${completed} completed`,
  overdueDetail: (count) => `${count} high-priority`,
  trendTitle: 'Planned and completed rhythm',
  trendDescription: 'Tasks planned for each period compared with actual completions',
  planned: 'Planned',
  completed: 'Completed',
  insightsEyebrow: 'Worth attention',
  insightsTitle: 'From data to next steps',
  stableTitle: 'More consistent days',
  stableDescription: (days, advantage) => `${days} are ${advantage} points above the period average.`,
  pressureInsightTitle: (project) => `${project} has accumulated work`,
  pressureInsightDescription: (pending, overdue) => `${pending} pending, including ${overdue} overdue.`,
  reduceTitle: 'Planning suggestion',
  reduceDescription: (day, gap) => `${day} averages ${gap} fewer completions; reduce the planned load.`,
  buildingTitle: 'Building your history',
  buildingDescription: 'Keep planning and completing tasks to generate actionable patterns.',
  viewTasks: 'View related tasks',
  pressureTitle: 'Task pressure distribution',
  pressureDescription: 'Which projects contributed completions and which still have backlog',
  pending: 'Pending',
  weeklyTitle: 'Weekly pattern',
  weeklyDescription: 'Completion rate by planned weekday',
  noPlannedTasks: 'No planned tasks',
  weekdays: [
    'Sunday',
    'Monday',
    'Tuesday',
    'Wednesday',
    'Thursday',
    'Friday',
    'Saturday',
  ],
  definition: 'Planned completion = completed planned tasks in the period ÷ all planned tasks in the period. Trashed tasks are excluded and aggregation stays local.',
  estimatedDefinition: 'This range includes migrated history. Older reopen and reschedule activity may be incomplete; events after the upgrade are recorded accurately.',
};
