import type { Translation } from '../../types';
type CommonContent = Pick<Translation, 'appName' | 'tagline' | 'navigation' | 'search' | 'account' | 'signedOut' | 'notifications' | 'cancel' | 'delete' | 'clear'>;
export const common: CommonContent = {
  appName: 'LightFlux',
  tagline: 'Make space for what matters',
  navigation: {
    today: 'Today',
    completed: 'Completed',
    calendar: 'Calendar',
    milestones: 'Milestones',
    projects: 'Projects',
    trash: 'Trash',
  },
  search: {
    title: 'Search tasks',
    placeholder: 'Type a keyword…',
    clear: 'Clear search',
    close: 'Close search',
    tasks: 'Tasks',
    shortcut: 'Esc to close · Enter to open task',
    resultCount: (count) => `${count} ${count === 1 ? 'result' : 'results'}`,
    idleTitle: 'Find your tasks',
    idleDescription: 'Search by title, task details, or project name.',
    emptyTitle: 'No tasks found',
    emptyDescription: 'Try another keyword or check whether the task is in trash.',
  },
  account: {
    localAccount: 'Local account',
    settings: 'Settings',
    signOut: 'Sign out',
    signOutTitle: 'Sign out of this session?',
    signOutMessage: 'Your tasks will remain on this device and will be available when you return.',
  },
  signedOut: {
    title: 'Sign in to LightFlux',
    description: 'Use a password or email code to securely sync tasks across devices.',
    continue: 'Continue locally',
    passwordMethod: 'Password',
    otpMethod: 'Email code',
    emailPlaceholder: 'Email address',
    passwordPlaceholder: 'Password (8+ characters)',
    showPassword: 'Show password',
    hidePassword: 'Hide password',
    signInWithPassword: 'Sign in',
    signingInWithPassword: 'Signing in…',
    registerWithPassword: 'Create account',
    registeringWithPassword: 'Creating account…',
    createAccount: 'New here? Create an account',
    useExistingAccount: 'Already registered? Sign in',
    passwordTooShort: 'Use at least 8 characters.',
    passwordSignInError: 'The email or password is incorrect.',
    registrationError: 'Unable to create the account; the email may be registered.',
    registrationCodeSent: 'We sent a code to verify your email.',
    registrationCodeDescription: (email) => `Enter the registration code sent to ${email}`,
    verifyRegistration: 'Verify and finish registration',
    sendCode: 'Send verification code',
    sendingCode: 'Sending…',
    codeDescription: (email) => `We sent a code to ${email}`,
    codePlaceholder: 'Enter the 6-digit code',
    verifyCode: 'Verify and sign in',
    verifyingCode: 'Verifying…',
    resendCode: 'Send again',
    changeEmail: 'Change email',
    codeSent: 'A new verification code was sent.',
    invalidEmail: 'Enter a valid email address.',
    invalidCode: 'Enter the complete 6-digit code.',
    requestError: 'Unable to send the code. Try again shortly.',
    verifyError: 'That code is invalid or expired. Try again.',
    setPasswordDescription:
      'Set a password so you can sign in with email and password next time.',
    passwordConfirmPlaceholder: 'Confirm password',
    setPasswordAction: 'Set password',
    settingPassword: 'Setting password…',
    skipPassword: 'Skip for now',
    passwordMismatch: 'The passwords do not match.',
    setPasswordError: 'Unable to set the password. Try again shortly.',
  },
  notifications: {
    orderUpdated: 'Order updated.',
    saveFailed: 'Save failed. Local data is preserved; try again later.',
    taskCompleted: [
      'Nicely done!',
      'One more off the list 🎉',
      'Great work — keep it up!',
      'Momentum looking good ✨',
      'Done! Give yourself credit.',
    ],
    allTasksDone: "Every task done today. You're on fire! 🎊",
    taskReopened: 'Marked as active again.',
    taskMovedToProject: (projectName) => `Moved to “${projectName}”.`,
    taskRescheduled: 'Date updated.',
    priorityUpdated: 'Priority updated.',
  },
  cancel: 'Cancel',
  delete: 'Delete',
  clear: 'Clear',
};
