import type { Translation } from '../../types';
export const milestones: Translation['milestones'] = {
  title: '倒数纪念日',
  count: (count) => `${count} 个节点`,
  add: '新增节点',
  addTemplate: '选择节点类型',
  templates: {
    anniversary: '纪念日',
    countdown: '倒数日',
    birthday: '生日',
    holiday: '节日',
    custom: '自定义',
  },
  filters: {
    all: '全部',
    anniversary: '纪念日',
    countdown: '倒数日',
    birthday: '生日',
    holiday: '节日',
    custom: '自定义',
    archived: '已归档',
  },
  emptyTitle: '还没有倒数或纪念日',
  emptyArchived: '没有已归档节点',
  titlePlaceholder: '节点名称',
  calendar: '历法',
  repeat: '重复',
  solar: '公历',
  lunar: '农历',
  repeatYearly: '每年重复',
  oneTime: '仅一次',
  year: '年份',
  month: '月份',
  day: '日期',
  startYear: '起始年份（可选）',
  notes: '备注',
  notesPlaceholder: '添加简短备注…',
  reminders: '提前提醒',
  reminderDay: (days) => (days === 0 ? '当天' : `提前 ${days} 天`),
  reminderToday: '今天就是这个重要节点',
  reminderInDays: (days) => `还有 ${days} 天`,
  leapMonth: '闰月',
  leapMonthFallback: '无闰月时按普通月份',
  leapMonthSkip: '无闰月时跳过该年',
  lunarDayThirtySkip: '农历小月没有三十时跳过该年',
  februaryFallback: '非闰年规则',
  february28: '按 2 月 28 日',
  march1: '按 3 月 1 日',
  style: '主题颜色',
  save: '保存节点',
  cancel: '取消',
  today: '今天',
  tomorrow: '明天',
  remainingDays: (days) => `还有 ${days} 天`,
  pastDays: (days) => `已过去 ${days} 天`,
  anniversaryYears: (years) => `第 ${years} 周年`,
  birthdayYears: (years) => `${years} 岁生日`,
  lunarDate: '农历',
  pinned: '置顶',
  archived: '已归档',
  edit: '编辑',
  pin: '置顶',
  unpin: '取消置顶',
  editStyle: '修改样式',
  editNotes: '编辑备注',
  createTask: '创建相关任务',
  archive: '归档',
  unarchive: '取消归档',
  moveToTrash: '移至垃圾桶',
  restored: '节点已恢复',
  trashed: '节点已移至垃圾桶',
  created: '节点已创建',
  updated: '节点已更新',
  relatedTaskCreated: '相关任务已创建',
  invalidDate: '请填写有效日期',
  notificationPermissionDenied: '需要允许系统通知才能启用提前提醒',
  moreActions: '更多节点操作',
  todaySection: '今天的节点',
  openMilestones: '查看倒数纪念日',
};
