import type { Translation } from '../../types';
export const editor: Translation['editor'] = {
  title: 'Task details',
  titlePlaceholder: 'Task title',
  bodyPlaceholder: 'Add notes, code, or images…',
  close: 'Back',
  bold: 'Bold',
  italic: 'Italic',
  heading: 'Heading',
  bulletList: 'Bullet list',
  orderedList: 'Ordered list',
  quote: 'Quote',
  inlineCode: 'Inline code',
  codeBlock: 'Code block',
  undo: 'Undo',
  redo: 'Redo',
  image: 'Image',
  imageUrl: 'Image URL (https://…)',
  insertImage: 'Insert image',
  invalidImageUrl: 'Enter a valid http or https image URL.',
  imageUploading: 'Uploading image…',
  imageUploadNotConfigured: 'Image upload is not configured.',
  imageUploadTooLarge: 'Images must be 8 MB or smaller.',
  imageUploadUnsupported: 'Use a PNG, JPEG, WebP, GIF, or AVIF image.',
  imageUploadFailed: 'Unable to upload the image. Try again.',
  emptyTitle: 'A task title is required.',
  previewTitle: 'Task preview',
  resizePane: 'Resize task list and details',
};
