import type { Translation } from '../../types';
export const editor: Translation['editor'] = {
  title: '任务详情',
  titlePlaceholder: '任务标题',
  bodyPlaceholder: '记录说明、代码或图片…',
  close: '返回',
  bold: '粗体',
  italic: '斜体',
  heading: '标题',
  bulletList: '无序列表',
  orderedList: '有序列表',
  quote: '引用',
  inlineCode: '行内代码',
  codeBlock: '代码块',
  undo: '撤销',
  redo: '重做',
  image: '图片',
  imageUrl: '图片 URL（https://…）',
  insertImage: '插入图片',
  invalidImageUrl: '请输入有效的 http 或 https 图片地址。',
  imageUploading: '正在上传图片…',
  imageUploadNotConfigured: '图片上传服务尚未配置。',
  imageUploadTooLarge: '图片不能超过 8 MB。',
  imageUploadUnsupported: '仅支持 PNG、JPEG、WebP、GIF 或 AVIF 图片。',
  imageUploadFailed: '图片上传失败，请稍后重试。',
  emptyTitle: '任务标题不能为空。',
  previewTitle: '任务预览',
  resizePane: '调整任务列表与详情宽度',
  metadataTitle: '任务信息',
  dateLabel: '日期',
  groupLabel: '分组',
  priorityLabel: '优先级',
  scheduleToday: '今天',
  scheduleTomorrow: '明天',
  clearDate: '清除日期',
  noDate: '未安排',
};
