import type { Translation } from '../../types';
export const desktop: Translation['desktop'] = {
  newVersionAvailable: (version) => `新版本 ${version} 可用`,
  updateToVersion: (version) => `更新到 ${version}`,
  settings: {
    subtitle: '界面、桌面端与工作方式偏好',
    general: '通用',
    languageDescription: '选择界面的显示语言',
    softwareUpdate: '软件更新',
    updateReminderOptions: {
      sidebarAndToast: '侧栏图标与一次提示',
      sidebar: '仅显示侧栏图标',
      settingsOnly: '仅在设置中显示',
    },
    dockVisibilityOptions: {
      always: '始终显示',
      windowOpen: '窗口打开时显示',
      hidden: '隐藏，使用菜单栏模式',
    },
    dockBadgeOptions: {
      today: '今日未完成任务',
      overdue: '仅延期任务',
      none: '不显示',
    },
    closeBehaviorOptions: {
      hide: '隐藏到菜单栏',
      quit: '退出 LightFlux',
    },
    updateChecking: '正在检查…',
    updateDownloading: (progress) => `正在下载 ${progress}%`,
    updateReady: '等待重启',
    updateAvailable: (version) => `${version} 可用`,
    updateCurrent: '已是最新版本',
    updateCheckedAtLaunch: '启动时自动检查',
    updateSigningRequired: '需要配置发布签名',
    tryAgain: '请稍后重试。',
    updateFallbackBody: '包含功能改进与稳定性修复。',
    updateCheckDescription: '每次启动后静默检查一次，不影响首屏加载',
    currentVersion: '当前版本',
    restartUpdate: '重启更新',
    downloadUpdate: '下载更新',
    checkNow: '立即检查',
    autoDownloadDescription: '普通更新在后台下载，完成后再提示重启',
    autoDownload: '后台下载更新',
    updateReminderDescription: '新版本到达时显示最小化快捷入口',
    updateReminder: '更新提醒位置',
    dockIconDescription: '选择运行时显示在 Dock 中的 LightFlux 图标',
    dockIcon: 'Dock 图标',
    dockIcons: {
      flux: '光流',
      paper: '纸白',
      graphite: '石墨',
    },
    dockVisibilityDescription: '隐藏 Dock 后仍可通过顶部菜单栏重新打开窗口',
    dockVisibility: 'Dock 显示方式',
    dockBadgeDescription: '在图标右上角显示最需要关注的任务数量',
    dockBadge: 'Dock 角标',
    closeBehaviorDescription: '菜单栏模式下可保持后台运行',
    closeBehavior: '关闭最后一个窗口时',
  },
  updateMenu: {
    ready: '更新已准备好',
    downloading: '正在下载更新',
    failed: '更新失败',
    available: (version) => `LightFlux ${version} 可用`,
    close: '关闭更新信息',
    currentVersion: (version) => `当前版本 ${version}`,
    required: '必要更新',
    stable: '稳定版本',
    tryAgain: '请稍后重试。',
    fallbackBody: '包含功能改进与稳定性修复。',
    later: '取消',
    skip: '跳过此版本',
    download: '立即更新',
    downloadingProgress: '正在下载…',
    restart: '重启并完成更新',
  },
};
