import type { Translation } from '../../types';
export const settings: Translation['settings'] = {
  title: 'Settings',
  languageTitle: 'Language',
  chinese: '简体中文',
  english: 'English',
  dataTitle: 'Data and statistics',
  statisticsTitle: 'Statistics',
  statisticsDescription: 'Review completion rhythm, task pressure, and planning patterns',
  shortcutsTitle: 'Keyboard shortcuts',
  shortcutSearch: 'Search tasks',
  shortcutClose: 'Close details or menus',
  shortcutBold: 'Bold',
  shortcutItalic: 'Italic',
  shortcutHeading: 'Heading 1',
  shortcutList: 'Bullet list',
  shortcutQuote: 'Quote',
  shortcutCode: 'Code block',
  keySearch: 'Cmd / Ctrl + F',
  keyClose: 'Esc',
  keyBold: 'Cmd / Ctrl + B',
  keyItalic: 'Cmd / Ctrl + I',
  keyHeading: '# + Space',
  keyList: '- + Space',
  keyQuote: '> + Space',
  keyCode: '``` + Space',
};
