import type { Translation } from '../../types';
export const settings: Translation['settings'] = {
  title: 'Settings',
  accountTitle: 'Account',
  localOnly: 'Local only',
  editProfileName: 'Edit account name',
  profileNamePlaceholder: 'Account name',
  saveProfile: 'Save account name',
  changeAvatar: 'Change profile photo',
  profileUpdated: 'Account profile updated',
  profileUpdateError: 'Unable to update the account profile. Try again.',
  avatarPermissionDenied: 'Photo access is required to choose a profile image.',
  avatarUploadError: 'Unable to upload the profile image. Try another image.',
  signIn: 'Sign in',
  signOut: 'Sign out',
  languageTitle: 'Language',
  chinese: '简体中文',
  english: 'English',
  dataTitle: 'Data and statistics',
  statisticsTitle: 'Statistics',
  visibleViewsTitle: 'Visible views',
};
